apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::333709868863:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NDZVOJ4EJOR2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::333709868863:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-29T20:26:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1731"
  uid: 8252a00a-9d7d-4b93-978d-308a215a30e4

